curl localhost:8080/register --data "email=piet@gmail.com&password=asdf32dhdrs9"
curl localhost:8080/register --data "email=otto@hotmail.com&password=ya5e89"
curl localhost:8080/register --data "email=jenny@gmail.com&password=asdfsdf32"
curl localhost:8080/register --data "email=felipe@yahoo.com.com&password=w4y9875y098"
curl localhost:8080/register --data "email=xiaopeng@tutanota.com.com&password=peng237fds89"
